[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/nullzero/Documents/repos/github.com/projects/llm_validator/migrations"